port: 7893
socks-port: 7894
redir-port: 7895
allow-lan: true
mode: rule
log-level: info
tcp-concurrent: true
external-controller: '127.0.0.1:9091'
secret: ''
# external-ui: (auto-configured by start.sh)

